theme: jekyll-theme-minimal
title: Augur.Guide
description: A friendly user guide to the prediction market protocol owned and operated by the people that use it.
logo: https://augur.guide/assets/images/Augur.png
show_downloads: false
google_analytics: UA-12186523-5
